const worldLanguageData = [
  {
    LanguageCodeGoogleTrans: "af",
    LanguageCode: "afr",
    LanguageEnglish: "Afrikaans",
    LanguageAutonym: "Afrikaans",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ZA ZA-NC ZA-WC NA",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Southern Africa",
    FlorishIconfilename: "afr-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ak",
    LanguageCode: "aka",
    LanguageEnglish: "Twi",
    LanguageAutonym: "Twi",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "GH-AH",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Western Africa",
    FlorishIconfilename: "aka-min.png"
  },
  {
    LanguageCodeGoogleTrans: "am",
    LanguageCode: "amh",
    LanguageEnglish: "Amharic",
    LanguageAutonym: "አማርኛ",
    LanguageScriptCode: "Ethi (430)",
    LanguageScriptAutonym: "ግዕዝ",
    LanguageUseCodes: "ET",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "amh-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ar",
    LanguageCode: "ara",
    LanguageEnglish: "Arabic",
    LanguageAutonym: "لْعَرَبِيَّةُ",
    LanguageScriptCode: "Arab (160)",
    LanguageScriptAutonym: "الْعَرَبِيَّة",
    LanguageUseCodes: "DZ BH TD KM DJ EG ER IQ JO KW LB LY MR MA OM PS QA SA SO SD SY TN AE YE TZ-07 TZ-11 TZ-15",
    WorldwideUse: "Worldwide",
    Continent: "Asia",
    ContinentAndRegion: "Southwestern Asia",
    FlorishIconfilename: "ara-min.png"
  },
  {
    LanguageCodeGoogleTrans: "as",
    LanguageCode: "asm",
    LanguageEnglish: "Assamese",
    LanguageAutonym: "অসমীয়া",
    LanguageScriptCode: "Beng (325)",
    LanguageScriptAutonym: "বাংলা",
    LanguageUseCodes: "IN-AS",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "asm-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ay",
    LanguageCode: "aym",
    LanguageEnglish: "Aymara",
    LanguageAutonym: "Aymar aru",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "BO PE",
    WorldwideUse: "",
    Continent: "South America",
    ContinentAndRegion: "South America",
    FlorishIconfilename: "aym-min.png"
  },
  {
    LanguageCodeGoogleTrans: "az",
    LanguageCode: "aze",
    LanguageEnglish: "Azerbaijani",
    LanguageAutonym: "Азәрбајҹан дили",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "AZ RU-DA",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southwestern Asia",
    FlorishIconfilename: "aze-min.png"
  },
  {
    LanguageCodeGoogleTrans: "be",
    LanguageCode: "bel",
    LanguageEnglish: "Belarusian",
    LanguageAutonym: "беларуская мова",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "BY PL",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Eastern Europe",
    FlorishIconfilename: "bel-min.png"
  },
  {
    LanguageCodeGoogleTrans: "bg",
    LanguageCode: "bul",
    LanguageEnglish: "Bulgarian",
    LanguageAutonym: "български език",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "BG",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southeastern Europe",
    FlorishIconfilename: "bul-min.png"
  },
  {
    LanguageCodeGoogleTrans: "bho",
    LanguageCode: "bho",
    LanguageEnglish: "Bhojpuri",
    LanguageAutonym: "भोजपुरी",
    LanguageScriptCode: "Deva (315)",
    LanguageScriptAutonym: "देवनागरी",
    LanguageUseCodes: "FJ IN-JH",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "bho-min.png"
  },
  {
    LanguageCodeGoogleTrans: "bm",
    LanguageCode: "bam",
    LanguageEnglish: "Bambara",
    LanguageAutonym: "Bámánánkán",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ML",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "bam-min.png"
  },
  {
    LanguageCodeGoogleTrans: "bn",
    LanguageCode: "ben",
    LanguageEnglish: "Bengali",
    LanguageAutonym: "বাংলা",
    LanguageScriptCode: "Beng (325)",
    LanguageScriptAutonym: "বাংলা",
    LanguageUseCodes: "BD IN-WB IN-TR IN-JH",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "ben-min.png"
  },
  {
    LanguageCodeGoogleTrans: "bs",
    LanguageCode: "bos",
    LanguageEnglish: "Bosnian",
    LanguageAutonym: "Bosanski",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "BA ME",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southeastern Europe",
    FlorishIconfilename: "bos-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ca",
    LanguageCode: "cat",
    LanguageEnglish: "Catalan",
    LanguageAutonym: "Català",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ES-CT ES-IB ES-VC AD IT-88",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southwestern Europe",
    FlorishIconfilename: "cat-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ceb",
    LanguageCode: "ceb",
    LanguageEnglish: "Cebuano",
    LanguageAutonym: "Binisaya",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "PH-07 PH-08 PH-09 PH-10 PH-11 PH-12 PH-13 PH",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "ceb-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ckb",
    LanguageCode: "ckb",
    LanguageEnglish: "Kurdish (Sorani)",
    LanguageAutonym: "سۆرانی",
    LanguageScriptCode: "Aran (161)",
    LanguageScriptAutonym: "نَسْتَعْلِیق",
    LanguageUseCodes: "IQ-KR",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southwestern Asia",
    FlorishIconfilename: "ckb-min.png"
  },
  {
    LanguageCodeGoogleTrans: "co",
    LanguageCode: "cos",
    LanguageEnglish: "Corsican",
    LanguageAutonym: "Corsu",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "FR-20R",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southern Europe",
    FlorishIconfilename: "cos-min.png"
  },
  {
    LanguageCodeGoogleTrans: "cs",
    LanguageCode: "ces",
    LanguageEnglish: "Czech",
    LanguageAutonym: "Čeština",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "CZ",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Central Europe",
    FlorishIconfilename: "ces-min.png"
  },
  {
    LanguageCodeGoogleTrans: "cy",
    LanguageCode: "cym",
    LanguageEnglish: "Welsh",
    LanguageAutonym: "Cymraeg",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "GB-WLS",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Western Europe",
    FlorishIconfilename: "cym-min.png"
  },
  {
    LanguageCodeGoogleTrans: "da",
    LanguageCode: "dan",
    LanguageEnglish: "Danish",
    LanguageAutonym: "Dansk",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "DK FO",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Northern Europe",
    FlorishIconfilename: "dan-min.png"
  },
  {
    LanguageCodeGoogleTrans: "de",
    LanguageCode: "deu",
    LanguageEnglish: "German",
    LanguageAutonym: "Deutsch",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "DE AT BE LI LU CH",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Central Europe",
    FlorishIconfilename: "deu-min.png"
  },
  {
    LanguageCodeGoogleTrans: "doi",
    LanguageCode: "doi",
    LanguageEnglish: "Dogri",
    LanguageAutonym: "डोगरी",
    LanguageScriptCode: "Deva (315)",
    LanguageScriptAutonym: "देवनागरी",
    LanguageUseCodes: "IN-JK",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "doi-min.png"
  },
  {
    LanguageCodeGoogleTrans: "dv",
    LanguageCode: "div",
    LanguageEnglish: "Dhivehi",
    LanguageAutonym: "ދިވެހި,",
    LanguageScriptCode: "Thaa (170)",
    LanguageScriptAutonym: "ތާނަ",
    LanguageUseCodes: "MV",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "div-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ee",
    LanguageCode: "ewe",
    LanguageEnglish: "Ewe",
    LanguageAutonym: "Èʋegbe‎",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "*GH-TV GH-OT BJ-MO TG-M TG-P",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Western Africa",
    FlorishIconfilename: "ewe-min.png"
  },
  {
    LanguageCodeGoogleTrans: "el",
    LanguageCode: "ell",
    LanguageEnglish: "Greek",
    LanguageAutonym: "ελληνικά",
    LanguageScriptCode: "Grek (200)",
    LanguageScriptAutonym: "Ελληνικό",
    LanguageUseCodes: "GR CY",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southern Europe",
    FlorishIconfilename: "ell-min.png"
  },
  {
    LanguageCodeGoogleTrans: "en",
    LanguageCode: "eng",
    LanguageEnglish: "English",
    LanguageAutonym: "English",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "AG BB BZ BW BI CM CA DM SZ FJ GH GD GY IN IE JM KE KI LS LR MW MT MH MU FM NA NR NG PK PW PG PH RW KN LC VC WS SC SL SG SB ZA SS SD TZ BS GM TO TT TV UG VU ZM ZW",
    WorldwideUse: "Worldwide",
    Continent: "Europe",
    ContinentAndRegion: "Western Europe",
    FlorishIconfilename: "eng-min.png"
  },
  // {
  //   LanguageCodeGoogleTrans: "en",
  //   LanguageCode: "eng",
  //   LanguageEnglish: "English",
  //   LanguageAutonym: "English (Australian)",
  //   LanguageScriptCode: "Latn (215)",
  //   LanguageScriptAutonym: "Latin",
  //   LanguageUseCodes: "AU (AU-NSW AU-QLD AU-SA AU-TAS AU-VIC AU-WA AU-ACT AU-NT)",
  //   WorldwideUse: "Worldwide",
  //Continent: "Europe",
  //   ContinentAndRegion: "Western Europe",
  //   FlorishIconfilename: "eng-AU-min.png"
  // },
  // {
  //   LanguageCodeGoogleTrans: "en",
  //   LanguageCode: "eng",
  //   LanguageEnglish: "English",
  //   LanguageAutonym: "English (Canadian)",
  //   LanguageScriptCode: "Latn (215)",
  //   LanguageScriptAutonym: "Latin",
  //   LanguageUseCodes: "CA (CA-AB CA-BC CA-MB CA-NB CA-NL CA-NS CA-ON CA-PE CA-QC CA-SK CA-NT CA-NU CA-YT)",
  //   WorldwideUse: "Worldwide",
  //Continent: "Europe",
  //   ContinentAndRegion: "Western Europe",
  //   FlorishIconfilename: "eng-CA-min.png"
  // },
  // {
  //   LanguageCodeGoogleTrans: "en",
  //   LanguageCode: "eng",
  //   LanguageEnglish: "English",
  //   LanguageAutonym: "English (British)",
  //   LanguageScriptCode: "Latn (215)",
  //   LanguageScriptAutonym: "Latin",
  //   LanguageUseCodes: "GB (GB-ENG GB-NIR GB-SCT GB-WLS)",
  //   WorldwideUse: "Worldwide",
  //Continent: "Europe",
  //   ContinentAndRegion: "Western Europe",
  //   FlorishIconfilename: "eng-GB-min.png"
  // },
  // {
  //   LanguageCodeGoogleTrans: "en",
  //   LanguageCode: "eng",
  //   LanguageEnglish: "English",
  //   LanguageAutonym: "English (American)",
  //   LanguageScriptCode: "Latn (215)",
  //   LanguageScriptAutonym: "Latin",
  //   LanguageUseCodes: "US (US-AL US-AK US-AZ US-AR US-CA US-CO US-CT US-DE US-FL US-GA US-HI US-ID US-IL US-IN US-IA US-KS US-KY US-LA US-ME US-MD US-MA US-MI US-MN US-MS US-MO US-MT US-NE US-NV US-NH US-NJ US-NM US-NY US-NC US-ND US-OH US-OK US-OR US-PA US-RI US-SC US-SD US-TN US-TX US-UT US-VT US-VA US-WA US-WV US-WI US-WY US-DC US-AS US-GU US-MP US-PR US-UM US-VI)",
  //   WorldwideUse: "Worldwide",
  //Continent: "Europe",
  //   ContinentAndRegion: "Western Europe",
  //   FlorishIconfilename: "eng-US-min.png"
  // },
  {
    LanguageCodeGoogleTrans: "eo",
    LanguageCode: "epo",
    LanguageEnglish: "Esperanto",
    LanguageAutonym: "Esperanto",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "",
    WorldwideUse: "",
    Continent: "",
    ContinentAndRegion: "",
    FlorishIconfilename: "epo-min.png"
  },
  // {
  //   LanguageCodeGoogleTrans: "es",
  //   LanguageCode: "spa",
  //   LanguageEnglish: "Spanish",
  //   LanguageAutonym: "Español",
  //   LanguageScriptCode: "Latn (215)",
  //   LanguageScriptAutonym: "Latin",
  //   LanguageUseCodes: "419 AR BO CL CO CR CU DO EC SV GQ GT HN MX NI PA PE UY VE US-PR US-TX US-FL US-AZ US-NM US-CA",
  //   WorldwideUse: "Worldwide",
  //Continent: "Europe",
  //   ContinentAndRegion: "Southwestern Europe",
  //   FlorishIconfilename: "spa-419-min.png"
  // },
  {
    LanguageCodeGoogleTrans: "es",
    LanguageCode: "spa",
    LanguageEnglish: "Spanish",
    LanguageAutonym: "Español",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ES AR BO CL CO CR CU DO EC SV GQ GT HN MX NI PA PE UY VE US-PR US-TX US-FL US-AZ US-NM US-CA",
    WorldwideUse: "Worldwide",
    Continent: "Europe",
    ContinentAndRegion: "Southwestern Europe",
    FlorishIconfilename: "spa-419-min.png"
  },
  {
    LanguageCodeGoogleTrans: "et",
    LanguageCode: "est",
    LanguageEnglish: "Estonian",
    LanguageAutonym: "Eesti Keel",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "EE",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Eastern Europe",
    FlorishIconfilename: "est-min.png"
  },
  {
    LanguageCodeGoogleTrans: "eu",
    LanguageCode: "eus",
    LanguageEnglish: "Basque",
    LanguageAutonym: "Euskara",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ES-PV ES-NA",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southwestern Europe",
    FlorishIconfilename: "eus-min.png"
  },
  {
    LanguageCodeGoogleTrans: "fa",
    LanguageCode: "fas",
    LanguageEnglish: "Persian",
    LanguageAutonym: "فارسی",
    LanguageScriptCode: "Aran (161)",
    LanguageScriptAutonym: "نَسْتَعْلِیق",
    LanguageUseCodes: "IR AF TJ RU-DA",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southwestern Asia",
    FlorishIconfilename: "fas-min.png"
  },
  {
    LanguageCodeGoogleTrans: "fi",
    LanguageCode: "fin",
    LanguageEnglish: "Finnish",
    LanguageAutonym: "Suomi",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "FI",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Northern Europe",
    FlorishIconfilename: "fin-min.png"
  },
  {
    LanguageCodeGoogleTrans: "fr",
    LanguageCode: "fra",
    LanguageEnglish: "French",
    LanguageAutonym: "Français",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "FR BJ BF CG CD CI GA GN MC NE SN TG CH-GE CH-JU CH-NE CH-VD CH-VS CA-QC BE BE-WAL BE-BRU BI CM CA TD CF KM DJ GQ HT LU MG RW SC CH VU IT-23 CH-BE CH-FR JE CA-NB CA-NT CA-NU IN-PY CA-YT US-LA",
    WorldwideUse: "Worldwide",
    Continent: "Europe",
    ContinentAndRegion: "Western Europe",
    FlorishIconfilename: "fra-min.png"
  },
  {
    LanguageCodeGoogleTrans: "fy",
    LanguageCode: "fry",
    LanguageEnglish: "Frisian",
    LanguageAutonym: "Frysk",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "NL-FR",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Western Europe",
    FlorishIconfilename: "fry-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ga",
    LanguageCode: "gle",
    LanguageEnglish: "Irish",
    LanguageAutonym: "Gaelic",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "IE GB-NIR",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Western Europe",
    FlorishIconfilename: "gle-min.png"
  },
  {
    LanguageCodeGoogleTrans: "gd",
    LanguageCode: "gla",
    LanguageEnglish: "Scots Gaelic",
    LanguageAutonym: "Gàidhlig",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "GB-SCT",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Western Europe",
    FlorishIconfilename: "gla-min.png"
  },
  {
    LanguageCodeGoogleTrans: "gl",
    LanguageCode: "glg",
    LanguageEnglish: "Galician",
    LanguageAutonym: "Galego",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ES-GA",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southwestern Europe",
    FlorishIconfilename: "glg-min.png"
  },
  {
    LanguageCodeGoogleTrans: "gn",
    LanguageCode: "grn",
    LanguageEnglish: "Guarani",
    LanguageAutonym: "Avañeʼẽ",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "PY BO AR-W",
    WorldwideUse: "",
    Continent: "South America",
    ContinentAndRegion: "South America",
    FlorishIconfilename: "grn-min.png"
  },
  {
    LanguageCodeGoogleTrans: "gom",
    LanguageCode: "gom",
    LanguageEnglish: "Konkani",
    LanguageAutonym: "कोंकणी",
    LanguageScriptCode: "Deva (315)",
    LanguageScriptAutonym: "देवनागरी",
    LanguageUseCodes: "IN-GA",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "gom-min.png"
  },
  {
    LanguageCodeGoogleTrans: "gu",
    LanguageCode: "guj",
    LanguageEnglish: "Gujarati",
    LanguageAutonym: "ગુજરાતી",
    LanguageScriptCode: "Gujr\t(320)",
    LanguageScriptAutonym: "ગુજરાતી લિપિ",
    LanguageUseCodes: "IN-GJ IN-DH",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "guj-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ha",
    LanguageCode: "hau",
    LanguageEnglish: "Hausa",
    LanguageAutonym: "Harshen",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "NG NE",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Western Africa",
    FlorishIconfilename: "hau-min.png"
  },
  {
    LanguageCodeGoogleTrans: "haw",
    LanguageCode: "haw",
    LanguageEnglish: "Hawaiian",
    LanguageAutonym: "ʻŌlelo Hawaiʻi",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "US-HI",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "haw-min.png"
  },
  {
    LanguageCodeGoogleTrans: "hi",
    LanguageCode: "hin",
    LanguageEnglish: "Hindi",
    LanguageAutonym: "हिन्दी",
    LanguageScriptCode: "Deva (315)",
    LanguageScriptAutonym: "देवनागरी",
    LanguageUseCodes: "IN",
    WorldwideUse: "Worldwide",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "hin-min.png"
  },
  {
    LanguageCodeGoogleTrans: "hmn",
    LanguageCode: "hmn",
    LanguageEnglish: "Hmong",
    LanguageAutonym: "lus Hmoob",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "CN LA MM VN TH",
    WorldwideUse: "",
    Continent: "Asia",
    Continent: "Asia",
    ContinentAndRegion: "Southeastern Asia",
    FlorishIconfilename: "hmn-min.png"
  },
  {
    LanguageCodeGoogleTrans: "hr",
    LanguageCode: "hrv",
    LanguageEnglish: "Croatian",
    LanguageAutonym: "Hrvatski",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "HR BA ME RS-VO AT-1",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southeastern Europe",
    FlorishIconfilename: "hrv-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ht",
    LanguageCode: "hat",
    LanguageEnglish: "Haitian Creole",
    LanguageAutonym: "Kreyòl Ayisyen",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "HT",
    WorldwideUse: "",
    Continent: "North America",
    ContinentAndRegion: "North America",
    FlorishIconfilename: "hat-min.png"
  },
  {
    LanguageCodeGoogleTrans: "hu",
    LanguageCode: "hun",
    LanguageEnglish: "Hungarian",
    LanguageAutonym: "Magyar Nyelv",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "HU RS-VO AT-1 SI",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Central Europe",
    FlorishIconfilename: "hun-min.png"
  },
  {
    LanguageCodeGoogleTrans: "hy",
    LanguageCode: "hye",
    LanguageEnglish: "Armenian",
    LanguageAutonym: "հայերեն",
    LanguageScriptCode: "Arm (230)",
    LanguageScriptAutonym: "հայերեն",
    LanguageUseCodes: "AM",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southwestern Asia",
    FlorishIconfilename: "hye-min.png"
  },
  {
    LanguageCodeGoogleTrans: "id",
    LanguageCode: "ind",
    LanguageEnglish: "Indonesian",
    LanguageAutonym: "Bahasa Indonesia",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ID",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "ind-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ig",
    LanguageCode: "ibo",
    LanguageEnglish: "Igbo",
    LanguageAutonym: "Ásụ̀sụ́ Ìgbò",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "NG",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Western Africa",
    FlorishIconfilename: "ibo-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ilo",
    LanguageCode: "ilo",
    LanguageEnglish: "Ilocano",
    LanguageAutonym: "Ilokano",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "PH-01",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "ilo-min.png"
  },
  {
    LanguageCodeGoogleTrans: "is",
    LanguageCode: "isl",
    LanguageEnglish: "Icelandic",
    LanguageAutonym: "Íslenska",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "IS",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Northern Europe",
    FlorishIconfilename: "isl-min.png"
  },
  {
    LanguageCodeGoogleTrans: "it",
    LanguageCode: "ita",
    LanguageEnglish: "Italian",
    LanguageAutonym: "Italiano",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "IT SM CH VA SI HR-18",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southern Europe",
    FlorishIconfilename: "ita-min.png"
  },
  {
    LanguageCodeGoogleTrans: "iw",
    LanguageCode: "heb",
    LanguageEnglish: "Hebrew",
    LanguageAutonym: "עברית חדשה",
    LanguageScriptCode: "Hebr (125)",
    LanguageScriptAutonym: "עברית",
    LanguageUseCodes: "IL",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southwestern Asia",
    FlorishIconfilename: "heb-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ja",
    LanguageCode: "jpn",
    LanguageEnglish: "Japanese",
    LanguageAutonym: "日本語",
    LanguageScriptCode: "Jpan (413)",
    LanguageScriptAutonym: "日本語",
    LanguageUseCodes: "JP PW",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Eastern Asia",
    FlorishIconfilename: "jpn-min.png"
  },
  {
    LanguageCodeGoogleTrans: "jv",
    LanguageCode: "jav",
    LanguageEnglish: "Javanese",
    LanguageAutonym: "Basa Jawa",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ID-JW",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "jav-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ka",
    LanguageCode: "kat",
    LanguageEnglish: "Georgian",
    LanguageAutonym: "ქართული ენა",
    LanguageScriptCode: "Geo (240)",
    LanguageScriptAutonym: "ქართული",
    LanguageUseCodes: "GE",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southwestern Asia",
    FlorishIconfilename: "kat-min.png"
  },
  {
    LanguageCodeGoogleTrans: "kk",
    LanguageCode: "kaz",
    LanguageEnglish: "Kazakh",
    LanguageAutonym: "қазақша",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "KZ RU-AL CN-XJ-40 CN-XJ-23 CN-XJ-05 CN-GS-09",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Central Asia",
    FlorishIconfilename: "kaz-min.png"
  },
  {
    LanguageCodeGoogleTrans: "km",
    LanguageCode: "khm",
    LanguageEnglish: "Khmer",
    LanguageAutonym: "ភាសាខ្មែរ",
    LanguageScriptCode: "Khmr (355)",
    LanguageScriptAutonym: "អក្សរខ្មែរ",
    LanguageUseCodes: "KH",
    WorldwideUse: "",
    Continent: "Asia",
    Continent: "Asia",
    ContinentAndRegion: "Southeastern Asia",
    FlorishIconfilename: "khm-min.png"
  },
  {
    LanguageCodeGoogleTrans: "kn",
    LanguageCode: "kan",
    LanguageEnglish: "Kannflourish",
    LanguageAutonym: "ಕನ್ನಡ",
    LanguageScriptCode: "Knda (345)",
    LanguageScriptAutonym: "ಕನ್ನಡ",
    LanguageUseCodes: "IN-KA",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "kan-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ko",
    LanguageCode: "kor",
    LanguageEnglish: "Korean",
    LanguageAutonym: "한국어",
    LanguageScriptCode: "Hang (286)",
    LanguageScriptAutonym: "한국어",
    LanguageUseCodes: "KO KP",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Eastern Asia",
    FlorishIconfilename: "kor-KO-min.png"
  },
  {
    LanguageCodeGoogleTrans: "kri",
    LanguageCode: "kri",
    LanguageEnglish: "Krio",
    LanguageAutonym: "Krio",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "SL",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Western Africa",
    FlorishIconfilename: "kri-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ku",
    LanguageCode: "kur",
    LanguageEnglish: "Kurdish (Kurmanji)",
    LanguageAutonym: "Kurmancî",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "IQ-KR",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southwestern Asia",
    FlorishIconfilename: "kur-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ky",
    LanguageCode: "kir",
    LanguageEnglish: "Kyrgyz",
    LanguageAutonym: "Кыргыз тили",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "KG CN-XJ-30",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Central Asia",
    FlorishIconfilename: "kir-min.png"
  },
  {
    LanguageCodeGoogleTrans: "la",
    LanguageCode: "lat",
    LanguageEnglish: "Latin",
    LanguageAutonym: "Latīnum",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "VA",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southern Europe",
    FlorishIconfilename: "lat-min.png"
  },
  {
    LanguageCodeGoogleTrans: "lb",
    LanguageCode: "ltz",
    LanguageEnglish: "Luxembourgish",
    LanguageAutonym: "Lëtzebuergesch",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "LU",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Western Europe",
    FlorishIconfilename: "ltz-min.png"
  },
  {
    LanguageCodeGoogleTrans: "lg",
    LanguageCode: "lug",
    LanguageEnglish: "Luganda",
    LanguageAutonym: "Oluganda",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "UG-C",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "lug-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ln",
    LanguageCode: "lin",
    LanguageEnglish: "Lingala",
    LanguageAutonym: "Lingála",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "CD CG",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Central Africa",
    FlorishIconfilename: "lin-min.png"
  },
  {
    LanguageCodeGoogleTrans: "lo",
    LanguageCode: "lao",
    LanguageEnglish: "Lao",
    LanguageAutonym: "ພາສາລາວ",
    LanguageScriptCode: "Laoo (356)",
    LanguageScriptAutonym: "ອັກສອນລາວ",
    LanguageUseCodes: "LA",
    WorldwideUse: "",
    Continent: "Asia",
    Continent: "Asia",
    ContinentAndRegion: "Southeastern Asia",
    FlorishIconfilename: "lao-min.png"
  },
  {
    LanguageCodeGoogleTrans: "lt",
    LanguageCode: "lit",
    LanguageEnglish: "Lithuanian",
    LanguageAutonym: "Lietuvių Kalba",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "LT",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Eastern Europe",
    FlorishIconfilename: "lit-min.png"
  },
  {
    LanguageCodeGoogleTrans: "lus",
    LanguageCode: "lus",
    LanguageEnglish: "Mizo",
    LanguageAutonym: "Mizo ṭawng",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "IN-MZ",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "lus-min.png"
  },
  {
    LanguageCodeGoogleTrans: "lv",
    LanguageCode: "lav",
    LanguageEnglish: "Latvian",
    LanguageAutonym: "Latviešu Valoda",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "LV",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Eastern Europe",
    FlorishIconfilename: "lav-min.png"
  },
  {
    LanguageCodeGoogleTrans: "mai",
    LanguageCode: "mai",
    LanguageEnglish: "Maithili",
    LanguageAutonym: "मैथिली",
    LanguageScriptCode: "Deva (315)",
    LanguageScriptAutonym: "देवनागरी",
    LanguageUseCodes: "IN-JK",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "mai-min.png"
  },
  {
    LanguageCodeGoogleTrans: "mg",
    LanguageCode: "mlg",
    LanguageEnglish: "Malagasy",
    LanguageAutonym: "Malagasy",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "MG",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "mlg-min.png"
  },
  {
    LanguageCodeGoogleTrans: "mi",
    LanguageCode: "mri",
    LanguageEnglish: "Maori",
    LanguageAutonym: "Te Reo Māori",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "NZ",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "mri-min.png"
  },
  {
    LanguageCodeGoogleTrans: "mk",
    LanguageCode: "mkd",
    LanguageEnglish: "Macedonian",
    LanguageAutonym: "македонски",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "MK",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southeastern Europe",
    FlorishIconfilename: "mkd-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ml",
    LanguageCode: "mal",
    LanguageEnglish: "Malayalam",
    LanguageAutonym: "മലയാളം",
    LanguageScriptCode: "Mlym (347)",
    LanguageScriptAutonym: "യാള ലിപി",
    LanguageUseCodes: "IN-KL IN-PY",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "mal-min.png"
  },
  {
    LanguageCodeGoogleTrans: "mn",
    LanguageCode: "mon",
    LanguageEnglish: "Mongolian",
    LanguageAutonym: "монгол хэл",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "MN CN-MN CN-XJ-27 CN-XJ-28 CN-XJ-42 CN-QH-28",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Central Asia",
    FlorishIconfilename: "mon-min.png"
  },
  {
    LanguageCodeGoogleTrans: "mni-Mtei",
    LanguageCode: "mni",
    LanguageEnglish: "Meiteilon (Manipuri)",
    LanguageAutonym: "Meiteilon",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "IN-MN",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "mni-min.png"
  },
  {
    LanguageCodeGoogleTrans: "mr",
    LanguageCode: "mar",
    LanguageEnglish: "Marathi",
    LanguageAutonym: "मराठी",
    LanguageScriptCode: "Deva (315)",
    LanguageScriptAutonym: "देवनागरी",
    LanguageUseCodes: "IN-MH IN-GA",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "mar-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ms",
    LanguageCode: "msa",
    LanguageEnglish: "Malay",
    LanguageAutonym: "Bahasa Melayu",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "MY BN SG",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "msa-min.png"
  },
  {
    LanguageCodeGoogleTrans: "mt",
    LanguageCode: "mlt",
    LanguageEnglish: "Maltese",
    LanguageAutonym: "Malti",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "MT",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southern Europe",
    FlorishIconfilename: "mlt-min.png"
  },
  {
    LanguageCodeGoogleTrans: "my",
    LanguageCode: "mya",
    LanguageEnglish: "Myanmar (Burmese)",
    LanguageAutonym: "မြန်မာစာ",
    LanguageScriptCode: "Mymr (350)",
    LanguageScriptAutonym: "အက္ခရ်မန်ဗၟ",
    LanguageUseCodes: "MM",
    WorldwideUse: "",
    Continent: "Asia",
    Continent: "Asia",
    ContinentAndRegion: "Southeastern Asia",
    FlorishIconfilename: "mya-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ne",
    LanguageCode: "nep",
    LanguageEnglish: "Nepali",
    LanguageAutonym: "नेपाली",
    LanguageScriptCode: "Deva (315)",
    LanguageScriptAutonym: "देवनागरी",
    LanguageUseCodes: "NP IN-SK IN-WB",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "nep-min.png"
  },
  {
    LanguageCodeGoogleTrans: "nl",
    LanguageCode: "nld",
    LanguageEnglish: "Dutch",
    LanguageAutonym: "Nederlands",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "NL BE SR NL-AW NL-CW NL-SX",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Western Europe",
    FlorishIconfilename: "nld-min.png"
  },
  {
    LanguageCodeGoogleTrans: "no",
    LanguageCode: "nor",
    LanguageEnglish: "Norwegian",
    LanguageAutonym: "Norsk",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "NO",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Northern Europe",
    FlorishIconfilename: "nor-min.png"
  },
  {
    LanguageCodeGoogleTrans: "nso",
    LanguageCode: "nso",
    LanguageEnglish: "Sepedi",
    LanguageAutonym: "Sepedi",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ZA",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Southern Africa",
    FlorishIconfilename: "nso-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ny",
    LanguageCode: "nya",
    LanguageEnglish: "Chichewa",
    LanguageAutonym: "Chichewa",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "MW ZW *ZM-03 MZ-A MZ-T",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "nya-min.png"
  },
  {
    LanguageCodeGoogleTrans: "om",
    LanguageCode: "orm",
    LanguageEnglish: "Oromo",
    LanguageAutonym: "Afaan Oromoo",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ET *KE",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "orm-min.png"
  },
  {
    LanguageCodeGoogleTrans: "or",
    LanguageCode: "ori",
    LanguageEnglish: "Odia (Oriya)",
    LanguageAutonym: "ଓଡ଼ିଆ",
    LanguageScriptCode: "Orya (327)",
    LanguageScriptAutonym: "ଓଡ଼ିଆ ଅକ୍ଷର",
    LanguageUseCodes: "IN-OR IN-JH IN-WB",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "ori-min.png"
  },
  {
    LanguageCodeGoogleTrans: "pa",
    LanguageCode: "pan",
    LanguageEnglish: "Punjabi",
    LanguageAutonym: "ਪੰਜਾਬੀ",
    LanguageScriptCode: "Guru (310)",
    LanguageScriptAutonym: "ਗੁਰਮੁਖੀ",
    LanguageUseCodes: "PK-PB IN-PB IN-HR IN-DL IN-WB",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "pan-min.png"
  },
  {
    LanguageCodeGoogleTrans: "pl",
    LanguageCode: "pol",
    LanguageEnglish: "Polish",
    LanguageAutonym: "Polski",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "PL",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Central Europe",
    FlorishIconfilename: "pol-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ps",
    LanguageCode: "pus",
    LanguageEnglish: "Pashto",
    LanguageAutonym: "پښتو",
    LanguageScriptCode: "Aran (161)",
    LanguageScriptAutonym: "نَسْتَعْلِیق",
    LanguageUseCodes: "AF PK",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "pus-min.png"
  },
  {
    LanguageCodeGoogleTrans: "pt",
    LanguageCode: "por",
    LanguageEnglish: "Portuguese (Brazil)",
    LanguageAutonym: "Português",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "PT BZ CV TL GQ GW MZ ST MO UY ZA",
    WorldwideUse: "Worldwide",
    Continent: "Europe",
    ContinentAndRegion: "Southwestern Europe",
    FlorishIconfilename: "por-min.png"
  },
  {
    LanguageCodeGoogleTrans: "qu",
    LanguageCode: "que",
    LanguageEnglish: "Quechua",
    LanguageAutonym: "Urin qichwa",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "BO AR-G *EC",
    WorldwideUse: "",
    Continent: "South America",
    ContinentAndRegion: "South America",
    FlorishIconfilename: "que-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ro",
    LanguageCode: "ron",
    LanguageEnglish: "Romanian",
    LanguageAutonym: "Românește",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "RO MD RS-VO",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southeastern Europe",
    FlorishIconfilename: "ron-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ru",
    LanguageCode: "rus",
    LanguageEnglish: "Russian",
    LanguageAutonym: "русский язык",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "RU BY KZ KG TJ",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Eastern Europe",
    FlorishIconfilename: "rus-min.png"
  },
  {
    LanguageCodeGoogleTrans: "rw",
    LanguageCode: "kin",
    LanguageEnglish: "Kinyarwanda",
    LanguageAutonym: "Ikinyarwanda",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "RW",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "kin-min.png"
  },
  {
    LanguageCodeGoogleTrans: "sa",
    LanguageCode: "san",
    LanguageEnglish: "Sanskrit",
    LanguageAutonym: "संस्कृतम्",
    LanguageScriptCode: "Deva (315)",
    LanguageScriptAutonym: "देवनागरी",
    LanguageUseCodes: "IN IN-HP IN-UT",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "san-min.png"
  },
  {
    LanguageCodeGoogleTrans: "sd",
    LanguageCode: "snd",
    LanguageEnglish: "Sindhi",
    LanguageAutonym: "سِنڌِي",
    LanguageScriptCode: "Aran (161)",
    LanguageScriptAutonym: "نَسْتَعْلِیق",
    LanguageUseCodes: "PK-SD IN",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "snd-min.png"
  },
  {
    LanguageCodeGoogleTrans: "si",
    LanguageCode: "sin",
    LanguageEnglish: "Sinhala",
    LanguageAutonym: "සිංහල",
    LanguageScriptCode: "Sinh (348)",
    LanguageScriptAutonym: "සිංහල අක්ෂර මාලාව",
    LanguageUseCodes: "LK",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "sin-min.png"
  },
  {
    LanguageCodeGoogleTrans: "sk",
    LanguageCode: "slk",
    LanguageEnglish: "Slovak",
    LanguageAutonym: "Slovenčina",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "SK RS-VO",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Central Europe",
    FlorishIconfilename: "slk-min.png"
  },
  {
    LanguageCodeGoogleTrans: "sl",
    LanguageCode: "slv",
    LanguageEnglish: "Slovenian",
    LanguageAutonym: "Slovenščina",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "SI",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Central Europe",
    FlorishIconfilename: "slv-min.png"
  },
  {
    LanguageCodeGoogleTrans: "sm",
    LanguageCode: "smo",
    LanguageEnglish: "Samoan",
    LanguageAutonym: "Gagana Faʻa Sāmoa",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "WS US-AS",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "smo-min.png"
  },
  {
    LanguageCodeGoogleTrans: "sn",
    LanguageCode: "sna",
    LanguageEnglish: "Shona",
    LanguageAutonym: "chiShona",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ZW *MZ",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "sna-min.png"
  },
  {
    LanguageCodeGoogleTrans: "so",
    LanguageCode: "som",
    LanguageEnglish: "Somali",
    LanguageAutonym: "Soomaali",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "SO DJ ET *KE",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "som-min.png"
  },
  {
    LanguageCodeGoogleTrans: "sq",
    LanguageCode: "sqi",
    LanguageEnglish: "Albanian",
    LanguageAutonym: "Shqipja",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "AL XK MK ME",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southeastern Europe",
    FlorishIconfilename: "sqi-min.png"
  },
  {
    LanguageCodeGoogleTrans: "sr",
    LanguageCode: "srp",
    LanguageEnglish: "Serbian",
    LanguageAutonym: "српски језик",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "RS BA ME XK",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Southeastern Europe",
    FlorishIconfilename: "srp-min.png"
  },
  {
    LanguageCodeGoogleTrans: "st",
    LanguageCode: "sot",
    LanguageEnglish: "Sesotho",
    LanguageAutonym: "Sesotho",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "LS ZA ZW",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Southern Africa",
    FlorishIconfilename: "sot-min.png"
  },
  {
    LanguageCodeGoogleTrans: "su",
    LanguageCode: "sun",
    LanguageEnglish: "Sundanese",
    LanguageAutonym: "Basa Sunda",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ID-JW ID-SM",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "sun-min.png"
  },
  {
    LanguageCodeGoogleTrans: "sv",
    LanguageCode: "swe",
    LanguageEnglish: "Swedish",
    LanguageAutonym: "Svenska",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "SE FI AX",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Northern Europe",
    FlorishIconfilename: "swe-min.png"
  },
  {
    LanguageCodeGoogleTrans: "sw",
    LanguageCode: "swa",
    LanguageEnglish: "Swahili",
    LanguageAutonym: "Kiswahili",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "TZ RW KE UG *BI CD MZ",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "swa-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ta",
    LanguageCode: "tam",
    LanguageEnglish: "Tamil",
    LanguageAutonym: "தமிழ்",
    LanguageScriptCode: "Taml (346)",
    LanguageScriptAutonym: "தமிழ் அரிச்சுவடி",
    LanguageUseCodes: "IN-TN IN-PY LK SG",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "tam-min.png"
  },
  {
    LanguageCodeGoogleTrans: "te",
    LanguageCode: "tel",
    LanguageEnglish: "Telugu",
    LanguageAutonym: "తెలుగు",
    LanguageScriptCode: "Telu (340)",
    LanguageScriptAutonym: "తెలుగు లిపి",
    LanguageUseCodes: "IN-AP IN-TG IN-PY IN-WB",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "tel-min.png"
  },
  {
    LanguageCodeGoogleTrans: "tg",
    LanguageCode: "tgk",
    LanguageEnglish: "Tajik",
    LanguageAutonym: "Тоҷикӣ",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "TJ",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Central Asia",
    FlorishIconfilename: "tgk-min.png"
  },
  {
    LanguageCodeGoogleTrans: "th",
    LanguageCode: "tha",
    LanguageEnglish: "Thai",
    LanguageAutonym: "ภาษาไทย",
    LanguageScriptCode: "Thai (352)",
    LanguageScriptAutonym: "อักษรไทย",
    LanguageUseCodes: "TH",
    WorldwideUse: "",
    Continent: "Asia",
    Continent: "Asia",
    ContinentAndRegion: "Southeastern Asia",
    FlorishIconfilename: "tha-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ti",
    LanguageCode: "tir",
    LanguageEnglish: "Tigrinya",
    LanguageAutonym: "ትግርኛ",
    LanguageScriptCode: "Ethi (430)",
    LanguageScriptAutonym: "ግዕዝ",
    LanguageUseCodes: "ER ET",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "tir-min.png"
  },
  {
    LanguageCodeGoogleTrans: "tk",
    LanguageCode: "tuk",
    LanguageEnglish: "Turkmen",
    LanguageAutonym: "türkmençe",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "TM",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Central Asia",
    FlorishIconfilename: "tuk-min.png"
  },
  {
    LanguageCodeGoogleTrans: "tl",
    LanguageCode: "tgl",
    LanguageEnglish: "Filipino",
    LanguageAutonym: "Tagalog",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "PH",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "tgl-min.png"
  },
  {
    LanguageCodeGoogleTrans: "tr",
    LanguageCode: "tur",
    LanguageEnglish: "Turkish",
    LanguageAutonym: "Türkçe",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "TR CY",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southwestern Asia",
    FlorishIconfilename: "tur-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ts",
    LanguageCode: "tso",
    LanguageEnglish: "Tsonga",
    LanguageAutonym: "Xitsonga",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ZA ZW *MZ",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Southern Africa",
    FlorishIconfilename: "tso-min.png"
  },
  {
    LanguageCodeGoogleTrans: "tt",
    LanguageCode: "tat",
    LanguageEnglish: "Tatar",
    LanguageAutonym: "татар теле",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "RU-TA",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Central Asia",
    FlorishIconfilename: "tat-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ug",
    LanguageCode: "uig",
    LanguageEnglish: "Uyghur",
    LanguageAutonym: "ئۇيغۇر تىلى",
    LanguageScriptCode: "Arab (160)",
    LanguageScriptAutonym: "الْعَرَبِيَّة",
    LanguageUseCodes: "CN-XJ",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Central Asia",
    FlorishIconfilename: "uig-min.png"
  },
  {
    LanguageCodeGoogleTrans: "uk",
    LanguageCode: "ukr",
    LanguageEnglish: "Ukrainian",
    LanguageAutonym: "українська мова",
    LanguageScriptCode: "Cyrl (220)",
    LanguageScriptAutonym: "Кириллица",
    LanguageUseCodes: "UA",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Eastern Europe",
    FlorishIconfilename: "ukr-min.png"
  },
  {
    LanguageCodeGoogleTrans: "ur",
    LanguageCode: "urd",
    LanguageEnglish: "Urdu",
    LanguageAutonym: "اردو",
    LanguageScriptCode: "Aran (161)",
    LanguageScriptAutonym: "نَسْتَعْلِیق",
    LanguageUseCodes: "PK IN-JK IN-JH IN-DL IN-BR IN-UP IN-AR IN-TG\tIN-WB",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southern Asia",
    FlorishIconfilename: "urd-min.png"
  },
  {
    LanguageCodeGoogleTrans: "uz",
    LanguageCode: "uzb",
    LanguageEnglish: "Uzbek",
    LanguageAutonym: "Oʻzbekcha",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "UZ",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Central Asia",
    FlorishIconfilename: "uzb-min.png"
  },
  {
    LanguageCodeGoogleTrans: "vi",
    LanguageCode: "vie",
    LanguageEnglish: "Vietnamese",
    LanguageAutonym: "Việt",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "VN",
    WorldwideUse: "",
    Continent: "Asia",
    Continent: "Asia",
    ContinentAndRegion: "Southeastern Asia",
    FlorishIconfilename: "vie-min.png"
  },
  {
    LanguageCodeGoogleTrans: "xh",
    LanguageCode: "xho",
    LanguageEnglish: "Xhosa",
    LanguageAutonym: "isiXhosa",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ZA ZW *BW",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Southern Africa",
    FlorishIconfilename: "xho-min.png"
  },
  {
    LanguageCodeGoogleTrans: "yi",
    LanguageCode: "yid",
    LanguageEnglish: "Yiddish",
    LanguageAutonym: "ייִדיש",
    LanguageScriptCode: "Hebr (125)",
    LanguageScriptAutonym: "עברית",
    LanguageUseCodes: "RU-YEV *BA DE IL NL PL RO SE UA RU",
    WorldwideUse: "",
    Continent: "Europe",
    ContinentAndRegion: "Central Europe",
    FlorishIconfilename: "yid-min.png"
  },
  {
    LanguageCodeGoogleTrans: "yo",
    LanguageCode: "yor",
    LanguageEnglish: "Yoruba",
    LanguageAutonym: "Èdè Yorùbá",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "NG",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Western Africa",
    FlorishIconfilename: "yor-min.png"
  },
  {
    LanguageCodeGoogleTrans: "zh-CN",
    LanguageCode: "zho",
    LanguageEnglish: "Chinese (Simplified)",
    LanguageAutonym: "简体字",
    LanguageScriptCode: "Hans (501)",
    LanguageScriptAutonym: "简化字",
    LanguageUseCodes: "CN SG",
    WorldwideUse: "Worldwide",
    Continent: "Asia",
    ContinentAndRegion: "Eastern Asia",
    FlorishIconfilename: "zho-CN-min.png"
  },
  {
    LanguageCodeGoogleTrans: "zh-TW",
    LanguageCode: "zho",
    LanguageEnglish: "Chinese (Traditional)",
    LanguageAutonym: "繁体字",
    LanguageScriptCode: "Hant (502)",
    LanguageScriptAutonym: "正體字",
    LanguageUseCodes: "TW HK MO",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Eastern Asia",
    FlorishIconfilename: "zho-TW-min.png"
  },
  {
    LanguageCodeGoogleTrans: "zu",
    LanguageCode: "zul",
    LanguageEnglish: "Zulu",
    LanguageAutonym: "isiZulu",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "ZA",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Southern Africa",
    FlorishIconfilename: "zul-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "run",
    LanguageEnglish: "Rundi",
    LanguageAutonym: "Ikirundi",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "BI",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Eastern Africa",
    FlorishIconfilename: "run-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "bsq",
    LanguageEnglish: "Bassa",
    LanguageAutonym: "Ɓǎsɔ́ɔ̀",
    LanguageScriptCode: "Bass (259)",
    LanguageScriptAutonym: "ɓǎsɔ́ɔ̀",
    LanguageUseCodes: "LR CI SL",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Western Africa",
    FlorishIconfilename: "bsq-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "ffm",
    LanguageEnglish: "Fula",
    LanguageAutonym: "𞤊𞤵𞤤𞤬𞤵𞤤𞤣𞤫",
    LanguageScriptCode: "Adlm (166)",
    LanguageScriptAutonym: "𞤀𞤣𞤤𞤢𞤥 𞤆𞤵𞤤𞤢𞤪",
    LanguageUseCodes: "ML",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Western Africa",
    FlorishIconfilename: "ffm-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "din",
    LanguageEnglish: "Dinka",
    LanguageAutonym: "Thuɔŋjäŋ",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "SS",
    WorldwideUse: "",
    Continent: "Africa",
    ContinentAndRegion: "Western Africa",
    FlorishIconfilename: "din-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "kar",
    LanguageEnglish: "Karen",
    LanguageAutonym: "Karen",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "*MM TH",
    WorldwideUse: "",
    Continent: "Asia",
    Continent: "Asia",
    ContinentAndRegion: "Southeastern Asia",
    FlorishIconfilename: "kar-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "syr",
    LanguageEnglish: "Suret",
    LanguageAutonym: "ܣܘܪܝܬ",
    LanguageScriptCode: "Syrc (135)",
    LanguageScriptAutonym: "ܐܠܦ ܒܝܬ ܣܘܪܝܝܐ",
    LanguageUseCodes: "IQ",
    WorldwideUse: "",
    Continent: "Asia",
    ContinentAndRegion: "Southwestern Asia",
    FlorishIconfilename: "syr-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "pdc",
    LanguageEnglish: "Pennsylvania Dutch",
    LanguageAutonym: "Pennsilfaanisch Deitsche",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "*US-PA",
    WorldwideUse: "",
    Continent: "North America",
    ContinentAndRegion: "North America",
    FlorishIconfilename: "pdc-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "mus",
    LanguageEnglish: "Creek (Muscogee)",
    LanguageAutonym: "Mvskoke",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "*US-AL US-FL US-OK",
    WorldwideUse: "",
    Continent: "North America",
    ContinentAndRegion: "North America",
    FlorishIconfilename: "mus-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "mik",
    LanguageEnglish: "Mikisúkî",
    LanguageAutonym: "Hitchiti",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "*US-FL",
    WorldwideUse: "",
    Continent: "North America",
    ContinentAndRegion: "North America",
    FlorishIconfilename: "mik-3-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "cho",
    LanguageEnglish: "Choctaw",
    LanguageAutonym: "Chahta anumpa",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "*US-MS US-OK",
    WorldwideUse: "",
    Continent: "North America",
    ContinentAndRegion: "North America",
    FlorishIconfilename: "cho-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "chr",
    LanguageEnglish: "Cherokee",
    LanguageAutonym: "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ",
    LanguageScriptCode: "Cher (445)",
    LanguageScriptAutonym: "ᏣᎳᎩ",
    LanguageUseCodes: "*US-NC US-OK",
    WorldwideUse: "",
    Continent: "North America",
    ContinentAndRegion: "North America",
    FlorishIconfilename: "chr-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "nav",
    LanguageEnglish: "Navajo",
    LanguageAutonym: "Diné Bizaad",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "*US-NM US-AZ US-UT US-CO",
    WorldwideUse: "",
    Continent: "North America",
    ContinentAndRegion: "North America",
    FlorishIconfilename: "nav-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "pon",
    LanguageEnglish: "Pohnpeian",
    LanguageAutonym: "Lokaiahn Pohnpei",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "FM-PNI",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "pon-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "chk",
    LanguageEnglish: "Chuukese",
    LanguageAutonym: "Chuuk",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "FM-TRK",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "chk-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "mah",
    LanguageEnglish: "Marshallese",
    LanguageAutonym: "Kajin M̧ajeļ",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "MH",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "mah-min.png"
  },
  {
    LanguageCodeGoogleTrans: "",
    LanguageCode: "ton",
    LanguageEnglish: "Tongan",
    LanguageAutonym: "ea faka-Tonga",
    LanguageScriptCode: "Latn (215)",
    LanguageScriptAutonym: "Latin",
    LanguageUseCodes: "TO",
    WorldwideUse: "",
    Continent: "Oceania",
    ContinentAndRegion: "Oceania",
    FlorishIconfilename: "ton-min.png"
  }
]

